apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick-ui
  labels:
    app: falcosidekick-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcosidekick-ui
  template:
    metadata:
      labels:
        app: falcosidekick-ui
    spec:
      containers:
      - name: falcosidekick-ui
        image: falcosecurity/falcosidekick-ui:latest
        ports:
        - containerPort: 2802
---
apiVersion: v1
kind: Service
metadata:
  name: falcosidekick-ui
  labels:
    app: falcosidekick-ui
spec:
  type: NodePort
  ports:
  - port: 2802
    targetPort: 2802
    nodePort: 30002  # Choose a NodePort in the range 30000-32767
  selector:
    app: falcosidekick-ui
